### ISSUE TITLE
Can I run this project without TPU on Ubuntu?

### ISSUE THREAD

**Issue by JiageWang** [google-coral/project-bodypix#1]

**Comment by mbrooksx** [comment]
We only provided the EdgeTPU models, however it's easy to also provide the non-compiled tflite for generic platforms. I'll track that as a feature request.

In the meantime the best way is to use the in-broswer TF.js example on your Ubuntu machine: https://storage.googleapis.com/tfjs-models/demos/body-pix/index.html
