### ISSUE TITLE
Can I try to convert bodypix tflite/tfjs model to tf pb?

### ISSUE THREAD

**Issue by tbjszhu** [google-coral/project-bodypix#11]
Hi,

I found the bodypix tfjs live demo is very fascinating and I am very interested in this network.  Can I try to covert this bodypix tflite/tfjs model to tensorflow pb frozen model to do some demo (not for commercial use)? Thanks for your attention.

**Comment by Namburger** [comment]
@tbjszhu Hello, thanks for the inputs.
Unfortunately, there is no way to convert a tflite back to pb and at this time we haven't made plan to share the training process for this model :/

**Comment by tbjszhu** [comment]
@Namburger Hi Namburger,

Thanks for the reply. 
Oh, maybe I didn't asked in a clear way, I'm not trying to get the training stage. : -D.
So for the bodypix tfjs live demo in https://github.com/tensorflow/tfjs-models/tree/master/body-pix, the tfjs model of this demo is stored in some path under https://storage.googleapis.com/tfjs-models and is pretty readable and understandable.  I think it could be interesting if I could give it a shot to convert it to tf frozen model and do some forward inference demo only. Does this idea seem OK to you ?

**Comment by tbjszhu** [comment]
For short, do the models under https://storage.googleapis.com/tfjs-models/savedmodel/bodypix/ follow the save license as the bodypix project, which is Apache License 2.0 ?

**Comment by Namburger** [comment]
Hello, actually, I don't know much about the tfjs model 
@mbrooksx do you have any idea?

**Comment by mbrooksx** [comment]
It's not possible to go from TFLite to TF but it is possible to go from
TF.js. I believe https://github.com/patlevin/tfjs-to-tf has been previously
used for Bodypix, but I haven't tried it.

**Comment by tbjszhu** [comment]
@mbrooksx Hi mbrooksx,

Thanks for your reply.
Then we will use the tfjs model converted to do some demo  :-D

**Comment by Naveen-Dodda** [comment]
Closing this as the information to full fill the requirement has been shared. Please feel free to reopen if you have more questions.
