### ISSUE TITLE
Is this compatible with Eagle 5.0 & pycoral API?

### ISSUE THREAD

**Issue by BrewLink** [google-coral/project-bodypix#12]
Looks like it's complaining for "edgetpu" => ModuleNotFoundError: No module named 'edgetpu'

Is there a quick workaround for using the previous API instead? Like flashing Day 13? 

Thx

**Comment by Namburger** [comment]
Hello, yes, we are working on getting this repo fixed ASAP with our new API.
For now, please use my fork: https://github.com/Namburger/project-posenet

**Comment by manoj7410** [comment]
@mike122112 Is this issue still reproducible ?
