### ISSUE TITLE
BodyPix - TensorFlow Lite Question

### ISSUE THREAD

**Issue by josh-nathanson** [google-coral/project-bodypix#13]
Hi it appears the BodyPix is in js.  Is it possible and functionable to convert to tensorflow lite? Also Can it work using a Mac cpu or windows gpu if we want to build in the cloud for application scaling? 

Thank you so much.

Josh

**Comment by Naveen-Dodda** [comment]
@josh-nathanson 

I Think this issue has been filed at wrong place. Regarding TF.js and cloud applications of bodypix, can you contact https://github.com/tensorflow/tfjs-models/blob/master/body-pix/README.md .

Hope you have already asked your question relevant group, I am closing this for now.
