### ISSUE TITLE
TF lite version

### ISSUE THREAD

**Issue by dvk17are** [google-coral/project-bodypix#14]
Hi, thanks for your great work guys :) 
It would be nice if you also release the tflite models from the previous stage.
I am currently working on decoding the output without BasicEngine and I would like to test it on CPU only with the tflite interpreter.

With the TPU version, tensors are not allocated due to custom operations:
interpreter= Interpreter(model_path='bodypix_resnet_50_640_480_16_quant_edgetpu_decoder.tflite')
interpreter.allocate_tensors()

Error : 
RuntimeError: Encountered unresolved custom op: edgetpu-custom-op.Node number 0 (edgetpu-custom-op) failed to prepare.
Encountered unresolved custom op: edgetpu-custom-op.Node number 0 (edgetpu-custom-op) failed to prepare.

**Comment by Namburger** [comment]
@dvk17are hello, you'll need to register the `posenet_decoder.so` like how I do it here: https://github.com/google-coral/project-posenet/blob/ugrade-to-frogfish/pose_engine.py#L79-L83

**Comment by Naveen-Dodda** [comment]
@dvk17are  answering your first question are you looking for cpu based bodypix models a step before edgetpu_compiler ?

if so they are [here](https://github.com/google-coral/project-posenet/tree/ugrade-to-frogfish/models). Model without _edgetpu.tfllite extension belongs to cpu.

**Comment by Naveen-Dodda** [comment]
I am closing this issue, as the request has been fulfilled. Please feel free to reopen if you have more questions
