### ISSUE TITLE
AttributeError: 'Delegate' object has no attribute '_library' - RPi4 + Coral USB

### ISSUE THREAD

**Issue by airqualityanthony** [google-coral/project-bodypix#17]
Hi, flagging this error when trying to run the bodypix.py script. 

Believe it's linked to 'OSError: posenet_lib/armv7l/posenet_decoder.so: cannot open shared object file: No such file or directory'7

Any help appreciated.

**Comment by airqualityanthony** [comment]
Actually I just noticed it's looking in armv7l and the repo saves armv7a - renaming folder seemed to let it run. Whether that was the correct fix or not I don't know...

**Comment by Namburger** [comment]
@airqualityanthony that is the fix :)

**Comment by queyrusi** [comment]
Saved my day, thanks!
