### ISSUE TITLE
No module named 'gi'

### ISSUE THREAD

**Issue by yangwenbing2** [google-coral/project-bodypix#21]
when i run the base demo (using the MobileNet v1 backbone with 640x480 input) :  python3 bodypix.py
i got an error : No module named 'gi'

but i can't install 'gi' package by "pip install gi", i want to know what is the module "gi"

my enviroment:
      - Mac OS
      - python: 3.6
      -

**Comment by fablau** [comment]
If you are not using a virtual environment, try this:

`install PyGObject`

If instead you are using something pipenv:

`pipenv install PyGObject`

I hope this helps!

**Comment by manoj7410** [comment]
@InnocentYang1 Were you able to fix this issue ?

**Comment by Eby-123** [comment]
I solve this problem by "sudo apt-get install libgirepository1.0-dev"
