### ISSUE TITLE
Does M.2 Accelerator with Dual Edge TPU work with RPI 4

### ISSUE THREAD

**Issue by manju-rn** [google-coral/project-bodypix#27]
Does M.2 Accelerator with Dual Edge TPU work with RPI 4 via the M.2 to USB adapter?  I believe this chip is better and cheaper than the USB version

**Comment by hjonnala** [comment]
It seems above query got answered here https://github.com/google-coral/edgetpu/issues/256#issuecomment-894645812

**Comment by magic-blue-smoke** [comment]
@manju-rn m.2 is like USB-C: same connector can carry USB, video or other interface.
There are two options for USB to m.2 adapters/ICs:
- USB to m.2 SATA - these adapters will not work as Dual Edge TPU needs PCIe interface
- USB to m.2 NVMe - in this case USB controller IC implements PCIe interface, but expects NVMe drive in terms of commands and data. Again, it will not work with Edge TPU

I'll be happy to be wrong here, but currently there is no adapter that passes/emulates PCIe over USB-C

For Raspberry Pi the only option is USB
