### ISSUE TITLE
Ask sharing the PosenetDecoderOp implementation for C++

### ISSUE THREAD

**Issue by seungchulhan** [google-coral/project-bodypix#28]
### Description

I want to use the bodypix in c++.
When I tested the bodypix model in c++, interpreter can't find the PosenetDecoderOp.
Could you share the c++ implementation for PosenetDecoderOp?
If there is a way to use bodypix model in c++ implementation, please let me know.
Thanks.

### Issue Type

Support

### Operating System

Ubuntu

### Coral Device

USB Accelerator

### Other Devices

Rapsberry Pi 4

### Programming Language

C++

**Comment by Namburger** [comment]
@seungchulhan here it is :) 
https://github.com/google-coral/libcoral/tree/master/coral/pose_estimation

the shared library is also available here if you don't wanna build it your self: https://github.com/google-coral/project-bodypix/tree/master/posenet_lib

**Comment by seungchulhan** [comment]
@Namburger 
I was referencing legacy code in edgetpu repo.
Its PosenetDecoderOp dose not support input num 4.
I fixed it with PosenetDecoderOp in libcoral repo.
Thanks !!!
