### ISSUE TITLE
How to run in headless mode

### ISSUE THREAD

**Issue by codyrushing** [google-coral/project-bodypix#29]
I am able to run the `bodypix_gl_imx.py` example on the Coral dev board using a USB webcam while connected to a monitor via HDMI.  However, when I disconnect my monitor and try to run this headless, I experience the following segmentation fault error:

```
(bodypix_gl_imx.py:4156): Gdk-CRITICAL **: 05:11:43.372: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed
bash: line 1:  4156 Segmentation fault      python3 bodypix_gl_imx.py --jpeg --model models/bodypix_mobilenet_v1_075_768_576_16_quant_edgetpu_decoder.tflite --videosrc /dev/video1 --width 1280 --height 720 --mirror
```

There seems to be a very similar issue in the googlecodelabs repo here https://github.com/googlecodelabs/edgetpu-classifier/issues/1.  However, none of the solutions proposed in that thread seem to apply here.

Has anyone been able to run the Coral bodypix example code without being connected to a display?  My application requires sending the heatmap and pose data via websockets to another program, so I don't need bodypix to render anything.

**Comment by hjonnala** [comment]
Hi, please refer to [examples-camera](https://github.com/google-coral/examples-camera/blob/master/gstreamer/gstreamer.py#L231) repo for headless implementation with Coral Dev Board.
