### ISSUE TITLE
Plans to implement this repository on the dev board mini

### ISSUE THREAD

**Issue by zain-altaf** [google-coral/project-bodypix#34]
### Description

Hi

I was wondering if this repository will be implemented for the dev board mini sometime?

Thanks

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Operating System

Mendel Linux

### Coral Device

Dev Board Mini

### Other Devices

Raspberry Pi 3

### Programming Language

Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Unfortunately, we don't have any plans to implement this project for dev board mini. Feel free to refer to [examples-camera repo](https://github.com/google-coral/examples-camera/blob/master/gstreamer/gstreamer.py#L248) to implement for dev board mini. Thanks!!
